---
all:
  hosts:
    host1:
      ansible_host: 192.168.121.222
      ansible_user: vagrant
      # ansible_password: almalinux@2024
      ansible_ssh_private_key_file: tests/.vagrant/machines/default/libvirt/private_key
