---

- name: "Configure ctrlaltdel | Disable ctrl+alt+del key restart computer"
  block:
    - name: "Configure ctrlaltdel | Disable ctrl+alt+del key restart computer | Mask ctrl-alt-del.target"
      ansible.builtin.systemd:
        name: ctrl-alt-del.target
        masked: true
        enabled: false
        state: stopped
        daemon_reload: true

    - name: "Configure ctrlaltdel | Disable ctrl+alt+del key restart computer | Set CtrlAltDelBurstAction to none"
      ansible.builtin.replace:
        path: /etc/systemd/system.conf
        regexp: '^#CtrlAltDelBurstAction=.*$'
        replace: 'CtrlAltDelBurstAction=none'
