---

- name: "SECURITY | Configure sshd"
  ansible.builtin.import_tasks:
    file: sshd.yml

- name: "SECURITY | Configure login"
  ansible.builtin.import_tasks:
    file: login.yml

- name: "SECURITY | Configure password complexity"
  ansible.builtin.import_tasks:
    file: password.yml

- name: "SECURITY | Configure user password"
  ansible.builtin.import_tasks:
    file: user.yml

- name: "SECURITY | Configure sudo"
  ansible.builtin.import_tasks:
    file: sudo.yml

- name: "SECURITY | Configure privilege"
  ansible.builtin.import_tasks:
    file: privilege.yml

- name: "SECURITY | Configure aliases"
  ansible.builtin.import_tasks:
    file: aliases.yml

- name: "SECURITY | Configure ps1"
  ansible.builtin.import_tasks:
    file: ps1.yml

- name: "SECURITY | Configure ctrlaltdel"
  ansible.builtin.import_tasks:
    file: ctrlaltdel.yml

- name: "SECURITY | Configure recyclebin"
  ansible.builtin.import_tasks:
    file: recyclebin.yml

- name: "SECURITY | Configure firewall"
  ansible.builtin.import_tasks:
    file: firewall.yml
  when: configure_firewall | default(true)
