---

- name: "Configure password complexity | Configure password days age"
  block:
    - name: "Configure password complexity | Configure password days age | Configure PASS_MIN_DAYS {{ pass_min_days }}"
      ansible.builtin.replace:
        path: /etc/login.defs
        regexp: "PASS_MIN_DAYS.*"
        replace: "PASS_MIN_DAYS {{ pass_min_days }}"

    - name: "Configure password complexity | Configure password days age | Configure PASS_MAX_DAYS {{ pass_max_days }}"
      ansible.builtin.replace:
        path: /etc/login.defs
        regexp: "PASS_MAX_DAYS.*"
        replace: "PASS_MAX_DAYS {{ pass_max_days }}"

    - name: "Configure password complexity | Configure password days age | Configure PASS_WARN_AGE {{ pass_warn_age }}"
      ansible.builtin.replace:
        path: /etc/login.defs
        regexp: "PASS_WARN_AGE.*"
        replace: "PASS_WARN_AGE {{ pass_warn_age }}"

    - name: "Configure password complexity | Configure password length | Configure PASS_MIN_LEN {{ pass_min_len }}"
      ansible.builtin.replace:
        path: /etc/login.defs
        regexp: "PASS_MIN_LEN.*"
        replace: "PASS_MIN_LEN {{ pass_min_len }}"

    - name: "Configure password complexity | Configure password encryption | Configure ENCRYPT_METHOD {{ pass_encrypt }}"
      ansible.builtin.replace:
        path: /etc/login.defs
        regexp: "ENCRYPT_METHOD.*"
        replace: "ENCRYPT_METHOD {{ pass_encrypt }}"

- name: "Configure password complexity | Configure password complexity settings"
  block:
    - name: "Configure password complexity | Configure password complexity settings | Configure password pam_pwquality.so"
      ansible.builtin.replace:
        path: /etc/pam.d/system-auth
        regexp: 'password\s+required\s+pam_pwquality.so'
        replace: 'password    requisite                                    pam_pwquality.so try_first_pass local_users_only enforce_for_root'

    - name: "Configure password complexity | Configure password complexity settings | Configure minlen = {{ pass_min_len }}"
      ansible.builtin.replace:
        path: /etc/security/pwquality.conf
        regexp: '^#?\s*minlen\s*=\s*\S*(\s*#.*)?\s*$'
        replace: "minlen = {{ pass_min_len }}"

    - name: "Configure password complexity | Configure password complexity settings | Configure retry = {{ pass_retry }}"
      ansible.builtin.replace:
        path: /etc/security/pwquality.conf
        regexp: '^#?\s*retry\s*=\s*\S*(\s*#.*)?\s*$'
        replace: "retry = {{ pass_retry }}"

    - name: "Configure password complexity | Configure password complexity settings | Configure difok = {{ pass_difok }}"
      ansible.builtin.replace:
        path: /etc/security/pwquality.conf
        regexp: '^#?\s*difok\s*=\s*\S*(\s*#.*)?\s*$'
        replace: "difok = {{ pass_difok }}"

    - name: "Configure password complexity | Configure password complexity settings | Configure minclass = {{ pass_minclass }}"
      ansible.builtin.replace:
        path: /etc/security/pwquality.conf
        regexp: '^#?\s*minclass\s*=\s*\S*(\s*#.*)?\s*$'
        replace: "minclass = {{ pass_minclass }}"

    - name: "Configure password complexity | Configure password complexity settings | Configure ucredit = {{ pass_ucredit }}"
      ansible.builtin.replace:
        path: /etc/security/pwquality.conf
        regexp: '^#?\s*ucredit\s*=\s*\S*(\s*#.*)?\s*$'
        replace: "ucredit = {{ pass_ucredit }}"

    - name: "Configure password complexity | Configure password complexity settings | Configure lcredit = {{ pass_lcredit }}"
      ansible.builtin.replace:
        path: /etc/security/pwquality.conf
        regexp: '^#?\s*lcredit\s*=\s*\S*(\s*#.*)?\s*$'
        replace: "lcredit = {{ pass_lcredit }}"

    - name: "Configure password complexity | Configure password complexity settings | Configure dcredit = {{ pass_dcredit }}"
      ansible.builtin.replace:
        path: /etc/security/pwquality.conf
        regexp: '^#?\s*dcredit\s*=\s*\S*(\s*#.*)?\s*$'
        replace: "dcredit = {{ pass_dcredit }}"

    - name: "Configure password complexity | Configure password complexity settings | Configure ocredit = {{ pass_ocredit }}"
      ansible.builtin.replace:
        path: /etc/security/pwquality.conf
        regexp: '^#?\s*ocredit\s*=\s*\S*(\s*#.*)?\s*$'
        replace: "ocredit = {{ pass_ocredit }}"

    - name: "Configure password complexity | Configure password complexity settings | Configure usercheck = 1"
      ansible.builtin.replace:
        path: /etc/security/pwquality.conf
        regexp: '^#?\s*usercheck\s*=\s*\S*(\s*#.*)?\s*$'
        replace: "usercheck = 1"

    - name: "Configure password complexity | Configure password complexity settings | Configure enforce_for_root"
      ansible.builtin.replace:
        path: /etc/security/pwquality.conf
        regexp: '^#?\s*enforce_for_root\s*=\s*\S*(\s*#.*)?\s*$'
        replace: "enforce_for_root"

    - name: "Configure password complexity | Configure password complexity settings | Configure remember = {{ pass_remember }}"
      ansible.builtin.replace:
        path: /etc/pam.d/system-auth
        regexp: 'password\s+sufficient\s+pam_unix.so'
        replace: "password    sufficient                                   pam_unix.so sha512 shadow nullok use_authtok remember={{ pass_remember }} enforce_for_root"
